# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "/page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
        path: ""
    values:
        title: Chouquette's blog

description: "Cones & Templates"
author:
  name: Hugo Beauzée-Luyssen
  email: hugo@beauzee.fr
  github: chouquette
  twitter: beauzeh
  linkedin: beauzeh
  bio:
      "Thoughts, rant, and articles from a software engineer"
  email_md5: a85112f5ec7d93095d49034cee7aecd1

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
