# Site settings
title: Chouquette's blog
header-img: img/banner.png
email: hugo@beauzee.fr
description: "Thoughts, rants, and articles from a VLC developer"
baseurl: ""
url: "http://www.beauzee.fr"
twitter_username: beauzeh
github_username:  chouquette

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
